version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.0.3

jobs:
  setup-test-azure:
    executor: azure-cli/azure-docker
    steps:
      - azure-cli/login-with-service-principal
      - run:
          name: Setup azure CLI for test subscription
          command: az account set -s "Test"
      - run:
          name: Create resource group
          command: az group create -n ${AZURE_TEST_RESOURCE_GROUP} --location westeurope
      - run:
          name: Set defaults
          command: az configure --defaults group=${AZURE_TEST_RESOURCE_GROUP}
      - run:
          name: Set defaults
          command: az group deployment create -n ${IDENTIFIER} --template-file ${TEMPLATE_FILE} --parameters ${PARAMETERS}
          environment:
            IDENTIFIER: ${AZURE_TEST_RESOURCE_GROUP}-${CIRCLE_BUILD_NUM}
            TEMPLATE_FILE: frontend/packages/cloud/azure-arm-template.json
            PARAMETERS: environment="test" serviceName=${PROJECT_NAME} dockerRegistryURL=${DOCKER_REGISTRY} dockerRegistryPassword=${DOCKER_REGISTRY_PASSWORD} dockerRegistryUsername=${DOCKER_REGISTRY_USERNAME}

  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: cd frontend && npm test

  deploy-production:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - run: echo "Deploying production..."

workflows:
  setup-test-workflow:
    jobs:
      - setup-test-azure

  release-production-workflow:
    jobs:
      - build
      - request-testing:
          type: approval
          requires:
            - build
      - deploy-production:
          requires:
            - request-testing
