version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.0.3

jobs:
  login-to-azure:
    executor: azure-cli/azure-docker
    steps:
      - azure-cli/login-with-service-principal

      - run:
          name: List resources of tenant stored as `AZURE_SP_TENANT` env var
          command: az resource list

  build:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - checkout
      - run: cd frontend && npm test

workflows:
  example-workflow:
    jobs:
      - login-to-azure
