###

POST http://127.0.0.1:8008/v1/identity/providers/<provider>/get-url
content-type: application/json

{
    "redirectUrl": "https://example.com/signed-in",
    "codeChallenge": "NTMsMjEsMjM4LDE4MiwyOCwxODksOTEsMTYwLDE1MiwxMTQsMjA1LDg2LDgxLDQwLDM1LDIyLDIxMSwyNDksMTc2LDE5MSwxNiwxMjAsMTcsMjgsMTEsMjAzLDQwLDYzLDIyOSw0OSwzMCwyNDQ="
}

###

post http://127.0.0.1:8008/v1/identity/providers/<provider>/authenticate
content-type: application/json

{
    "redirectUrl": "https://example.com/signed-in",
    "codeVerifier": "djfhsdkjfhsdkjfdjfhsdkjfhsdkjfsd",
    "code": "<code>"
}

###

POST http://127.0.0.1:8008/v1/identity/authenticate
content-type: application/json

{
    "email": "testmoversen@mover.dk",
    "password": "Test1234!"
}

###

POST http://127.0.0.1:8008/v1/identity/authorize
content-type: application/json
authorization: "Bearer <access-token>"

{
    "organizationId": "<organization-id>"
}

###

POST http://127.0.0.1:8008/v1/identity/reauthorize
content-type: application/json
authorization: "Bearer <access-token>"

{
    "refreshToken": "<refresh-token>"
}

###

POST http://127.0.0.1:8008/v1/identity/unauthenticate
content-type: application/json
authorization: "Bearer <access-token>"

{
    "refreshToken": "<refresh-token>"
}
