const body =
{
    accessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJvcmdhbml6YXRpb25fcGVybWlzc2lvbnMiOlsiY3JlYXRlLW9yZGVyIiwiZWRpdC1vcmRlciIsInZpZXctb3JkZXJzIiwiYWRkY29sbG8iLCJlZGl0LXJvdXRlcyIsInZpZXctcm91dGVzIiwiY3JlYXRlLWRlcGFydG1lbnRzIiwiZWRpdC1kZXBhcnRtZW50cyIsInZpZXctZGVwYXJ0bWVudHMiLCJjcmVhdGUtdXNlciIsImVkaXQtdXNlciIsInZpZXctdXNlcnMiLCJkZWFjdGl2YXRlLXVzZXIiLCJyZXNldC11c2VyLXBhc3N3b3JkIiwiY3JlYXRlLXJvdXRlcGxhbiIsImVkaXQtcm91dGVwbGFuIiwiY3JlYXRlLXJvdXRlcGxhbi1zZXR0aW5ncyIsInZpZXctcm91dGVwbGFucyIsImVkaXQtcm91dGVwbGFuLXNldHRpbmdzIiwidmlldy1yb3V0ZXBsYW4tc2V0dGluZ3MiLCJjcmVhdGUtdmVoaWNsZSIsImVkaXQtdmVoaWNsZSIsInZpZXctdmVoaWNsZXMiLCJpbnZpdGUtZHJpdmVyIiwiZWRpdC1kcml2ZXIiLCJ2aWV3LWRyaXZlcnMiLCJ2aWV3LWtwaXMiLCJ2aWV3LWFncmVlbWVudHMiLCJhc3NpZ25tZW50Iiwic2NhbmJhcmNvZGUiLCJjcmVhdGUtZGVwb3QiLCJlZGl0LWRlcG90Iiwidmlldy1kZXBvdCIsImNyZWF0ZS1mdWxmaWxsZXItZGlzcGF0Y2giLCJlZGl0LWZ1bGZpbGxlci1kaXNwYXRjaCIsInZpZXctZnVsZmlsbGVyLWRpc3BhdGNoIiwiY3JlYXRlLWZvcmVjYXN0IiwiZWRpdC1mb3JlY2FzdCIsInZpZXctZm9yZWNhc3QiLCJjcmVhdGUtcHJlYm9va2luZyIsImVkaXQtcHJlYm9va2luZyIsInZpZXctcHJlYm9va2luZyIsImNyZWF0ZS1hZ3JlZW1lbnQiLCJ2aWV3LWNvbW11bmljYXRpb24iLCJlZGl0LWNvbW11bmljYXRpb24iLCJ2aWV3LW9yZGVyLWdyb3VwcyIsImNyZWF0ZS1vcmRlci1ncm91cCIsImVkaXQtb3JkZXItZ3JvdXAiLCJ2aWV3LXJvdXRlLXRlbXBsYXRlcyIsImNyZWF0ZS1yb3V0ZS10ZW1wbGF0ZSIsImVkaXQtcm91dGUtdGVtcGxhdGUiLCJlZGl0LXJvdXRlcGxhbi1zaW11bGF0aW9ucyIsInZpZXctcm91dGVwbGFuLXNpbXVsYXRpb25zIiwiY3JlYXRlLXJvdXRlcGxhbi1zaW11bGF0aW9uIiwiYXNzaWduLWV4ZWN1dG9yLXJvdXRlIiwiYXNzaWduLWRyaXZlci1yb3V0ZSIsImFkbWluaXN0cmF0b3IiLCJkaXN0cmlidXRpb253b3JrZXIiXX0.hBfF6vHNtInUVMnZJivctvh22nM1vhfyW5L1OdVUZQc",
    refreshToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJvcmdhbml6YXRpb25fcGVybWlzc2lvbnMiOlsiY3JlYXRlLW9yZGVyIiwiZWRpdC1vcmRlciIsInZpZXctb3JkZXJzIiwiYWRkY29sbG8iLCJlZGl0LXJvdXRlcyIsInZpZXctcm91dGVzIiwiY3JlYXRlLWRlcGFydG1lbnRzIiwiZWRpdC1kZXBhcnRtZW50cyIsInZpZXctZGVwYXJ0bWVudHMiLCJjcmVhdGUtdXNlciIsImVkaXQtdXNlciIsInZpZXctdXNlcnMiLCJkZWFjdGl2YXRlLXVzZXIiLCJyZXNldC11c2VyLXBhc3N3b3JkIiwiY3JlYXRlLXJvdXRlcGxhbiIsImVkaXQtcm91dGVwbGFuIiwiY3JlYXRlLXJvdXRlcGxhbi1zZXR0aW5ncyIsInZpZXctcm91dGVwbGFucyIsImVkaXQtcm91dGVwbGFuLXNldHRpbmdzIiwidmlldy1yb3V0ZXBsYW4tc2V0dGluZ3MiLCJjcmVhdGUtdmVoaWNsZSIsImVkaXQtdmVoaWNsZSIsInZpZXctdmVoaWNsZXMiLCJpbnZpdGUtZHJpdmVyIiwiZWRpdC1kcml2ZXIiLCJ2aWV3LWRyaXZlcnMiLCJ2aWV3LWtwaXMiLCJ2aWV3LWFncmVlbWVudHMiLCJhc3NpZ25tZW50Iiwic2NhbmJhcmNvZGUiLCJjcmVhdGUtZGVwb3QiLCJlZGl0LWRlcG90Iiwidmlldy1kZXBvdCIsImNyZWF0ZS1mdWxmaWxsZXItZGlzcGF0Y2giLCJlZGl0LWZ1bGZpbGxlci1kaXNwYXRjaCIsInZpZXctZnVsZmlsbGVyLWRpc3BhdGNoIiwiY3JlYXRlLWZvcmVjYXN0IiwiZWRpdC1mb3JlY2FzdCIsInZpZXctZm9yZWNhc3QiLCJjcmVhdGUtcHJlYm9va2luZyIsImVkaXQtcHJlYm9va2luZyIsInZpZXctcHJlYm9va2luZyIsImNyZWF0ZS1hZ3JlZW1lbnQiLCJ2aWV3LWNvbW11bmljYXRpb24iLCJlZGl0LWNvbW11bmljYXRpb24iLCJ2aWV3LW9yZGVyLWdyb3VwcyIsImNyZWF0ZS1vcmRlci1ncm91cCIsImVkaXQtb3JkZXItZ3JvdXAiLCJ2aWV3LXJvdXRlLXRlbXBsYXRlcyIsImNyZWF0ZS1yb3V0ZS10ZW1wbGF0ZSIsImVkaXQtcm91dGUtdGVtcGxhdGUiLCJlZGl0LXJvdXRlcGxhbi1zaW11bGF0aW9ucyIsInZpZXctcm91dGVwbGFuLXNpbXVsYXRpb25zIiwiY3JlYXRlLXJvdXRlcGxhbi1zaW11bGF0aW9uIiwiYXNzaWduLWV4ZWN1dG9yLXJvdXRlIiwiYXNzaWduLWRyaXZlci1yb3V0ZSIsImFkbWluaXN0cmF0b3IiLCJkaXN0cmlidXRpb253b3JrZXIiXX0.hBfF6vHNtInUVMnZJivctvh22nM1vhfyW5L1OdVUZQc",
    id: "user-1-id",
    username: "john-doe@example.com",
    fullName: "John Doe",
    preferredName: "John",
    pictureUrl: undefined,
    outfit:
    {
        id: "mover-organization-id",
        companyName: "Mover"
    }
};

// tslint:disable
export default
{
    "POST /api/v2/identity/authenticate":
    {
        body: { ...body, outfit: undefined }
    },

    "POST /api/v2/identity/authorize":
    {
        body
    },

    "POST /api/v2/identity/reauthorize":
    {
        // Uncomment if reauthorization should fail.
        // status: 401

        // Uncomment if reauthorization should succeed.
        body
    },

    "POST /api/v2/identity/unauthenticate":
    {
        status: 204
    }
}
