# Configuration for `electron-builder`.

# Build configuration.

appId: com.mover

directories:
  buildResources: "resources/build"
  output: "artifacts/package"

files:

  # Include the build.
  - "artifacts/build"

  # Include resources.
  - "resources"

  # Exclude source maps.
  - "!**/*.map"

  # Exclude bundle analysis.
  - "!bundle-analysis.html"

# Platform configurations.

mac:
  target: "dmg"
  artifactName: "${productName} ${version}.${ext}"
  darkModeSupport: true

win:
  target: "nsis"
  artifactName: "${productName} Setup ${version}.${ext}"

linux:
  target: "AppImage"
  artifactName: "${productName} ${version}.${ext}"
