import placeholderDescriptions from "../strings/message-placeholder-descriptions.json";

export default
{
    "order-pickup-completed":
    {
        recipients:
        [
            "delivery-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "{OrderId}",
            "{DeliveryCustomerName}",
            "{PickupLocationAddress}",
            "{DeliveryLocationAddress}",
            "{DeliveryTimeFrame}",
            "{DriverPhone}",
            "{DriverName}",
            "{ETA}"
        ])
    },
    "order-delivery-arrived":
    {
        recipients:
        [
            "delivery-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "DeliveryCustomerName",
            "DeliveryLocationAddress",
            "DeliveryTimeFrame",
            "DriverPhone",
            "DriverName"
        ])
    },
    "eta-specific-time":
    {
        recipients:
        [
            "delivery-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "DeliveryCustomerName",
            "DeliveryLocationAddress",
            "DeliveryTimeFrame",
            "ETA"
        ])
    },
    "eta-before-delivery":
    {
        recipients:
        [
            "delivery-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "DeliveryCustomerName",
            "DeliveryLocationAddress",
            "DeliveryTimeFrame",
            "ETA",
            "DriverPhone",
            "DriverName"
        ])
    },
    "eta-before-pickup":
    {
        recipients:
        [
            "pickup-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "PickupCustomerName",
            "PickupLocationAddress",
            "PickupTimeFrame",
            "ETA",
            "DriverPhone",
            "DriverName"
        ])
    },
    "delayed-delivery":
    {
        recipients:
        [
            "delivery-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "DeliveryCustomerName",
            "DeliveryLocationAddress",
            "DeliveryTimeFrame",
            "ETA",
            "DriverPhone",
            "DriverName"
        ])
    },
    "delayed-pickup":
    {
        recipients:
        [
            "delivery-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "PickupCustomerName",
            "PickupLocationAddress",
            "PickupTimeFrame",
            "ETA",
            "DriverPhone",
            "DriverName"
        ])
    },
    "order-cancelled-en-route":
    {
        recipients:
        [
            "pickup-customer",
            "driver",
            "supplier"
        ],
        messageTypes:
        [
            "sms",
            "email",
            "push-to-driver-app"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "PickupCustomerName",
            "PickupLocationAddress",
            "DriverName",
            "DriverPhone",
            "DeliveryCustomerName",
            "DeliveryLocationAddress",
            "RouteReference",
            "RouteId"
        ])
    },
    "order-modified-en-rout":
    {
        recipients:
        [
            "driver",
            "supplier"
        ],
        messageTypes:
        [
            "sms",
            "email",
            "push-to-driver-app"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "PickupCustomerName",
            "PickupLocationAddress",
            "DriverName",
            "DriverPhone",
            "DeliveryCustomerName",
            "DeliveryLocationAddress",
            "StopNumber",
            "RouteReference",
            "RouteId"
        ])
    }
};

function getPlaceholders(placeholders: string[]): { placeholder: string; description: string }[]
{
    return placeholders.map(placeholder => ({ placeholder, description: placeholderDescriptions[placeholder] }));
}
