import placeholderDescriptions from "../strings/message-placeholder-descriptions.json";

export default
{
    "order-pickup-completed":
    {
        recipientTypes:
        [
            "delivery-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "DeliveryCustomerName",
            "PickupLocationAddress",
            "DeliveryLocationAddress",
            "DeliveryTimeFrame",
            "DriverPhone",
            "DriverName",
            "DeliveryEtaDate",
            "DeliveryEtaTime"
        ])
    },
    "order-delivery-arrived":
    {
        recipientTypes:
        [
            "delivery-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "DeliveryCustomerName",
            "DeliveryLocationAddress",
            "DeliveryTimeFrame",
            "DriverPhone",
            "DriverName"
        ])
    },
    "eta-specific-time":
    {
        recipientTypes:
        [
            "delivery-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "DeliveryCustomerName",
            "DeliveryLocationAddress",
            "DeliveryTimeFrame",
            "DeliveryEtaDate",
            "DeliveryEtaTime"
        ])
    },
    "eta-before-delivery":
    {
        recipientTypes:
        [
            "delivery-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "DeliveryCustomerName",
            "DeliveryLocationAddress",
            "DeliveryTimeFrame",
            "DeliveryEtaDate",
            "DeliveryEtaTime",
            "DriverPhone",
            "DriverName"
        ])
    },
    "eta-before-pickup":
    {
        recipientTypes:
        [
            "pickup-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "PickupCustomerName",
            "PickupLocationAddress",
            "PickupTimeFrame",
            "PickupEtaDate",
            "PickupEtaTime",
            "DriverPhone",
            "DriverName"
        ])
    },
    "delayed-delivery":
    {
        recipientTypes:
        [
            "delivery-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "DeliveryCustomerName",
            "DeliveryLocationAddress",
            "DeliveryTimeFrame",
            "DeliveryEtaDate",
            "DeliveryEtaTime",
            "DriverPhone",
            "DriverName"
        ])
    },
    "delayed-pickup":
    {
        recipientTypes:
        [
            "delivery-customer"
        ],
        messageTypes:
        [
            "sms",
            "email"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "PickupCustomerName",
            "PickupLocationAddress",
            "PickupTimeFrame",
            "PickupEtaDate",
            "PickupEtaTime",
            "DeliveryEtaDate",
            "DeliveryEtaTime",
            "DriverPhone",
            "DriverName"
        ])
    },
    "order-cancelled-en-route":
    {
        recipientTypes:
        [
            "pickup-customer",
            "driver",
            "supplier"
        ],
        messageTypes:
        [
            "sms",
            "email",
            "app-push"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "PickupCustomerName",
            "PickupLocationAddress",
            "DriverName",
            "DriverPhone",
            "DeliveryCustomerName",
            "DeliveryLocationAddress",
            "RouteReference",
            "RouteId"
        ])
    },
    "order-modified-en-rout":
    {
        recipientTypes:
        [
            "driver",
            "supplier"
        ],
        messageTypes:
        [
            "sms",
            "email",
            "app-push"
        ],
        placeholders: getPlaceholders(
        [
            "OrderId",
            "PickupCustomerName",
            "PickupLocationAddress",
            "DriverName",
            "DriverPhone",
            "DeliveryCustomerName",
            "DeliveryLocationAddress",
            "StopNumber",
            "RouteReference",
            "RouteId"
        ])
    }
};

function getPlaceholders(placeholders: string[]): { placeholder: string; description: string }[]
{
    return placeholders.map(placeholder => ({ placeholder: `{${placeholder}}`, description: placeholderDescriptions[placeholder] }));
}
