import { textCase } from "shared/utilities/text";

/**
 * Represents the slug identifying a `RouteStatus`, for use in a `RouteTemplate`.
 */
export type RouteStatusSlug = keyof typeof RouteStatus.values;

/**
 * Represents the status of a route when it is generated by a route template.
 */
export class RouteStatus
{
    /**
     * Creates a new instance of the type.
     * @param slug The slug identifying the status of the route.
     */
    public constructor(slug: RouteStatusSlug)
    {
        this.slug = textCase(slug, "pascal", "kebab") as any;
        Object.assign(this, RouteStatus.values[this.slug]);
    }

    public slug: RouteStatusSlug;
    public name: string;

    public static readonly values =
    {
        "requested":
        {
            name: "Requested"
        },
        "waiting-for-approval":
        {
            name: "Waiting for approval"
        }
    };
}
