phraseapp:
  access_token: 212eb4fa549d15dd609ad7283e67b5521da865996b1a99b04a6d3443aa9eb0bc
  push:
    sources:
      - file: ./packages/shared/src/localization/consignor/<locale_name>.json
        project_id: 970d8a1e6c441c6c888b3202a6b33634
        params:
          file_format: i18next
      - file: ./packages/shared/src/localization/operations/<locale_name>.json
        project_id: 86678a848f050eb18ed7aae556e93a5f
        params:
          file_format: i18next
      - file: ./packages/shared/src/localization/shared/<locale_name>.json
        project_id: b4002a9e666457ef182947a666df931c
        params:
          file_format: i18next
  pull:
    targets:
      - file: ./packages/shared/src/localization/consignor/<locale_name>.json
        project_id: 970d8a1e6c441c6c888b3202a6b33634
        params:
          file_format: i18next
      - file: ./packages/shared/src/localization/operations/<locale_name>.json
        project_id: 86678a848f050eb18ed7aae556e93a5f
        params:
          file_format: i18next
      - file: ./packages/shared/src/localization/shared/<locale_name>.json
        project_id: b4002a9e666457ef182947a666df931c
        params:
          file_format: i18next
